# Generated by Django 3.0.2 on 2020-01-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('santa_score', models.IntegerField()),
                ('elves_score', models.IntegerField()),
                ('mail_score', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
