# Generated by Django 3.0.2 on 2020-01-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickerhistory',
            name='date',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='clickerhistory',
            name='elves_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clickerhistory',
            name='mail_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clickerhistory',
            name='santa_score',
            field=models.IntegerField(default=0),
        ),
    ]
