# Generated by Django 2.2.7 on 2020-01-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200108_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickerhistory',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clickerhistory',
            name='elves_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clickerhistory',
            name='mail_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clickerhistory',
            name='santa_score',
            field=models.IntegerField(),
        ),
    ]
